force-exclude = true
line-length = 120
output-format = "grouped"
target-version = "py313"


[lint]
fixable = ["ALL"]
select = ["ALL"]
ignore = [
    'ANN002', 'ANN003',
    'COM812',
    'D100', 'D101', 'D103', 'D102', 'D104', 'D105', 'D106', "D107", "D400",
    'D203', 'D205',
    "G004",
    "TD001", ]

external = [
    "WPS114", "WPS115", "WPS117",
    "WPS210", "WPS211", "WPS214", "WPS221", "WPS226", "WPS230",
    "WPS323", "WPS301", "WPS235",
    "WPS428", "WPS432", "WPS437", "WPS465", "WPS474",
    "WPS601", "WPS603", "WPS604" ]

[lint.per-file-ignores]
"**/__init__.py" = ["F401", "F403"]
"tests/**/test_*.py" = ["F401", "S101", "S311", "F811"]

[lint.flake8-annotations]
mypy-init-return = true
ignore-fully-untyped = true
allow-star-arg-any = true
suppress-dummy-args = true

[lint.pydocstyle]
convention = "pep257"

[lint.isort]
force-wrap-aliases = true
force-sort-within-sections = true
combine-as-imports = true
lines-after-imports = 2
